/*!
 * Toolyard — tools-data.js
 * SINGLE SOURCE OF TRUTH for categories and tools.
 * Everything (navbar, mega menus, mobile menu, search, footer, breadcrumbs,
 * homepage sections, category pages) is rendered from this file by layout.js.
 *
 * ▸ To launch a tool: build the page at its `url`, then change status:'soon' → status:'live'.
 * ▸ To add a tool: add an object to TOOLS and its id to the category list in CATEGORY_TOOLS.
 * ▸ `also` lists extra categories a tool is shown in (e.g. CSS Grid Generator → generators).
 */
(function () {
  var CATEGORIES = [
    {"slug": "html-web", "name": "HTML & Web", "icon": "🌐", "folder": "html", "desc": "Format, validate, convert, audit and extract HTML markup.", "lead": "Browser-based HTML utilities to format, minify, validate, convert and audit markup — extract links, images, headings and meta tags without uploading a single byte."},
    {"slug": "css", "name": "CSS", "icon": "🎨", "folder": "css", "desc": "Format, minify and visually generate modern CSS.", "lead": "Beautify and compress stylesheets, then visually build gradients, shadows, grids, flexbox layouts, clip-paths, filters and more — copy production-ready CSS instantly."},
    {"slug": "javascript", "name": "JavaScript", "icon": "JS", "folder": "javascript", "desc": "Format, minify, validate and transform JavaScript.", "lead": "Format, minify and validate JavaScript, convert between JSON and JS objects, test regular expressions and escape strings — all executed locally in your browser."},
    {"slug": "json-data", "name": "JSON & Data", "icon": "{ }", "folder": "json-data", "desc": "Format, validate, compare and convert structured data.", "lead": "Format, validate, minify, compare and convert JSON, YAML, CSV and XML. Flatten objects, test JSON paths and validate schemas — 100% client-side."},
    {"slug": "developer", "name": "Developer", "icon": "⌨", "folder": "developer", "desc": "Encoders, decoders, hashes, JWT, UUID, regex and more.", "lead": "Everyday developer utilities: Base64 and URL encoding, JWT decoding, UUIDs, hashes, regex, timestamps, HTTP status codes, MIME types and cron expressions."},
    {"slug": "seo", "name": "SEO", "icon": "🔍", "folder": "seo", "desc": "Meta tags, schema markup, sitemaps and on-page analysis.", "lead": "Generate meta tags, Open Graph and Twitter cards, JSON-LD schema markup, robots.txt and sitemaps — then analyze headings, keywords and SERP snippets."},
    {"slug": "text", "name": "Text", "icon": "✎", "folder": "text", "desc": "Clean, sort, extract, compare and count text.", "lead": "Practical text utilities for developers and webmasters: dedupe and sort lines, extract emails and URLs, diff text, convert case, count words and generate slugs."},
    {"slug": "generators", "name": "Generators", "icon": "⚡", "folder": "generators", "desc": "Generate HTML, CSS components, favicons and SVG icons.", "lead": "Practical web-development generators — HTML boilerplates, tables and forms, CSS buttons, cards, loaders, modals, toggles, animations, favicons and SVG icons."},
  ];

  var TOOLS = [
    // ── HTML & Web ────────────────────────────────────────
    {"id": "html-validator", "name": "HTML Validator", "cat": "html-web", "badge": "Validator", "desc": "Check markup for unclosed tags, invalid nesting and common HTML errors.", "status": "soon", "url": "/tools/html/html-validator.html"},
    {"id": "html-formatter", "name": "HTML Formatter", "cat": "html-web", "badge": "Formatter", "desc": "Beautify messy markup with consistent indentation.", "status": "live", "url": "/tools/html/html-formatter.html", "popular": true},
    {"id": "html-minifier", "name": "HTML Minifier", "cat": "html-web", "badge": "Minifier", "desc": "Strip whitespace and comments to shrink file size.", "status": "live", "url": "/tools/html/html-minifier.html"},
    {"id": "html-to-markdown", "name": "HTML to Markdown", "cat": "html-web", "badge": "Converter", "desc": "Convert markup into clean, portable Markdown.", "status": "live", "url": "/tools/html/html-to-markdown.html", "popular": true},
    {"id": "html-to-text", "name": "HTML to Plain Text", "cat": "html-web", "badge": "Extractor", "desc": "Extract readable text from any HTML document.", "status": "live", "url": "/tools/html/html-to-text.html"},
    {"id": "html-to-jsx", "name": "HTML to JSX", "cat": "html-web", "badge": "Converter", "desc": "Turn HTML snippets into React-ready JSX.", "status": "live", "url": "/tools/html/html-to-jsx.html"},
    {"id": "html-to-css", "name": "HTML to CSS Extractor", "cat": "html-web", "badge": "Extractor", "desc": "Extract classes, IDs, inline styles and style blocks.", "status": "live", "url": "/tools/html/html-to-css.html"},
    {"id": "html-entity-encoder", "name": "HTML Entity Encoder", "cat": "html-web", "badge": "Encoder", "desc": "Encode special characters into HTML entities.", "status": "live", "url": "/tools/html/html-entity-encoder.html"},
    {"id": "html-entity-decoder", "name": "HTML Entity Decoder", "cat": "html-web", "badge": "Decoder", "desc": "Decode HTML entities back into readable characters.", "status": "soon", "url": "/tools/html/html-entity-decoder.html"},
    {"id": "html-link-extractor", "name": "HTML Link Extractor", "cat": "html-web", "badge": "Extractor", "desc": "Extract all links, anchors and URLs to CSV.", "status": "live", "url": "/tools/html/html-link-extractor.html"},
    {"id": "html-image-extractor", "name": "HTML Image Extractor", "cat": "html-web", "badge": "Extractor", "desc": "Audit image tags, dimensions and missing alt text.", "status": "live", "url": "/tools/html/html-image-extractor.html"},
    {"id": "html-heading-extractor", "name": "HTML Heading Extractor", "cat": "html-web", "badge": "Extractor", "desc": "List every H1–H6 heading to review page structure.", "status": "soon", "url": "/tools/html/html-heading-extractor.html"},
    {"id": "html-meta-tag-extractor", "name": "HTML Meta Tag Extractor", "cat": "html-web", "badge": "Extractor", "desc": "Pull title, description, Open Graph and other meta tags.", "status": "soon", "url": "/tools/html/html-meta-tag-extractor.html"},
    {"id": "html-comment-remover", "name": "HTML Comment Remover", "cat": "html-web", "badge": "Cleaner", "desc": "Strip all HTML comments while keeping markup intact.", "status": "soon", "url": "/tools/html/html-comment-remover.html"},
    {"id": "html-duplicate-id-checker", "name": "HTML Duplicate ID Checker", "cat": "html-web", "badge": "Checker", "desc": "Find duplicate id attributes that break scripts and a11y.", "status": "soon", "url": "/tools/html/html-duplicate-id-checker.html"},
    {"id": "html-favicon-extractor", "name": "HTML Favicon Extractor", "cat": "html-web", "badge": "Extractor", "desc": "Find every favicon, touch icon and manifest link.", "status": "soon", "url": "/tools/html/html-favicon-extractor.html"},
    // ── CSS ────────────────────────────────────────
    {"id": "css-formatter", "name": "CSS Formatter", "cat": "css", "badge": "Formatter", "desc": "Beautify, indent and format messy stylesheets.", "status": "live", "url": "/tools/css/css-formatter.html", "popular": true},
    {"id": "css-minifier", "name": "CSS Minifier", "cat": "css", "badge": "Minifier", "desc": "Compress stylesheets by stripping comments and whitespace.", "status": "live", "url": "/tools/css/css-minifier.html"},
    {"id": "css-gradient-generator", "name": "CSS Gradient Generator", "cat": "css", "badge": "Generator", "desc": "Build linear, radial and conic gradients visually.", "status": "soon", "url": "/tools/css/css-gradient-generator.html", "also": ["generators"]},
    {"id": "css-box-shadow-generator", "name": "CSS Box Shadow Generator", "cat": "css", "badge": "Generator", "desc": "Design layered box shadows with live preview.", "status": "soon", "url": "/tools/css/css-box-shadow-generator.html"},
    {"id": "css-border-radius-generator", "name": "CSS Border Radius Generator", "cat": "css", "badge": "Generator", "desc": "Shape corners individually and copy the CSS.", "status": "soon", "url": "/tools/css/css-border-radius-generator.html"},
    {"id": "css-flexbox-generator", "name": "CSS Flexbox Generator", "cat": "css", "badge": "Generator", "desc": "Configure flex containers and items visually.", "status": "soon", "url": "/tools/css/css-flexbox-generator.html", "also": ["generators"]},
    {"id": "css-grid-generator", "name": "CSS Grid Generator", "cat": "css", "badge": "Generator", "desc": "Draw grid layouts and export template CSS.", "status": "soon", "url": "/tools/css/css-grid-generator.html", "also": ["generators"]},
    {"id": "css-clip-path-generator", "name": "CSS Clip-Path Generator", "cat": "css", "badge": "Generator", "desc": "Create polygon, circle and inset clip-paths.", "status": "soon", "url": "/tools/css/css-clip-path-generator.html"},
    {"id": "css-transform-generator", "name": "CSS Transform Generator", "cat": "css", "badge": "Generator", "desc": "Combine rotate, scale, skew and translate.", "status": "soon", "url": "/tools/css/css-transform-generator.html"},
    {"id": "css-filter-generator", "name": "CSS Filter Generator", "cat": "css", "badge": "Generator", "desc": "Apply blur, contrast, hue and other filters.", "status": "soon", "url": "/tools/css/css-filter-generator.html"},
    {"id": "css-glassmorphism-generator", "name": "CSS Glassmorphism Generator", "cat": "css", "badge": "Generator", "desc": "Generate frosted-glass effects with backdrop-filter.", "status": "soon", "url": "/tools/css/css-glassmorphism-generator.html"},
    {"id": "css-neumorphism-generator", "name": "CSS Neumorphism Generator", "cat": "css", "badge": "Generator", "desc": "Create soft UI extruded and inset surfaces.", "status": "soon", "url": "/tools/css/css-neumorphism-generator.html"},
    {"id": "css-clamp-generator", "name": "CSS clamp() Generator", "cat": "css", "badge": "Generator", "desc": "Generate fluid typography and spacing with clamp().", "status": "soon", "url": "/tools/css/css-clamp-generator.html"},
    {"id": "css-media-query-generator", "name": "CSS Media Query Generator", "cat": "css", "badge": "Generator", "desc": "Build responsive breakpoints and media queries.", "status": "soon", "url": "/tools/css/css-media-query-generator.html"},
    {"id": "css-color-extractor", "name": "CSS Color Extractor", "cat": "css", "badge": "Extractor", "desc": "Extract every color value used in a stylesheet.", "status": "soon", "url": "/tools/css/css-color-extractor.html"},
    // ── JavaScript ────────────────────────────────────────
    {"id": "javascript-formatter", "name": "JavaScript Formatter", "cat": "javascript", "badge": "Formatter", "desc": "Beautify minified or messy JavaScript code.", "status": "soon", "url": "/tools/javascript/javascript-formatter.html"},
    {"id": "javascript-minifier", "name": "JavaScript Minifier", "cat": "javascript", "badge": "Minifier", "desc": "Compress JavaScript by removing whitespace and comments.", "status": "soon", "url": "/tools/javascript/javascript-minifier.html"},
    {"id": "javascript-validator", "name": "JavaScript Validator", "cat": "javascript", "badge": "Validator", "desc": "Detect syntax errors in JavaScript instantly.", "status": "soon", "url": "/tools/javascript/javascript-validator.html"},
    {"id": "json-js-object-converter", "name": "JSON ↔ JavaScript Object Converter", "cat": "javascript", "badge": "Converter", "desc": "Convert between strict JSON and JS object literals.", "status": "soon", "url": "/tools/javascript/json-js-object-converter.html"},
    {"id": "js-escape-unescape", "name": "JS Escape/Unescape", "cat": "javascript", "badge": "Encoder", "desc": "Escape or unescape strings for JavaScript source.", "status": "soon", "url": "/tools/javascript/js-escape-unescape.html"},
    {"id": "javascript-array-utilities", "name": "JavaScript Array Utilities", "cat": "javascript", "badge": "Utility", "desc": "Dedupe, sort, shuffle, chunk and flatten arrays.", "status": "soon", "url": "/tools/javascript/javascript-array-utilities.html"},
    {"id": "javascript-object-key-sorter", "name": "JavaScript Object Key Sorter", "cat": "javascript", "badge": "Utility", "desc": "Sort object keys alphabetically, deeply.", "status": "soon", "url": "/tools/javascript/javascript-object-key-sorter.html"},
    {"id": "javascript-regex-tester", "name": "JavaScript Regex Tester", "cat": "javascript", "badge": "Tester", "desc": "Test JS regular expressions with live match highlighting.", "status": "soon", "url": "/tools/javascript/javascript-regex-tester.html"},
    {"id": "js-timestamp-converter", "name": "JS Timestamp Converter", "cat": "javascript", "badge": "Converter", "desc": "Convert Date.now() milliseconds to readable dates.", "status": "soon", "url": "/tools/javascript/js-timestamp-converter.html"},
    {"id": "js-unicode-escape-tool", "name": "JS Unicode Escape Tool", "cat": "javascript", "badge": "Encoder", "desc": "Convert characters to \\uXXXX escape sequences.", "status": "soon", "url": "/tools/javascript/js-unicode-escape-tool.html"},
    // ── JSON & Data ────────────────────────────────────────
    {"id": "json-formatter", "name": "JSON Formatter", "cat": "json-data", "badge": "Formatter", "desc": "Format, indent, sort keys and validate JSON payloads.", "status": "live", "url": "/tools/json-data/json-formatter.html", "popular": true},
    {"id": "json-minifier", "name": "JSON Minifier", "cat": "json-data", "badge": "Minifier", "desc": "Strip whitespace to reduce JSON payload sizes.", "status": "live", "url": "/tools/json-data/json-minifier.html"},
    {"id": "json-to-yaml", "name": "JSON to YAML", "cat": "json-data", "badge": "Converter", "desc": "Convert JSON data into clean, indented YAML configs.", "status": "live", "url": "/tools/json-data/json-to-yaml.html", "popular": true},
    {"id": "yaml-to-json", "name": "YAML to JSON", "cat": "json-data", "badge": "Converter", "desc": "Parse YAML configuration files into valid JSON.", "status": "live", "url": "/tools/json-data/yaml-to-json.html"},
    {"id": "json-to-csv", "name": "JSON to CSV", "cat": "json-data", "badge": "Converter", "desc": "Convert nested or flat JSON arrays into tabular CSV.", "status": "live", "url": "/tools/json-data/json-to-csv.html"},
    {"id": "csv-to-json", "name": "CSV to JSON", "cat": "json-data", "badge": "Converter", "desc": "Parse tabular CSV data into structured JSON objects.", "status": "live", "url": "/tools/json-data/csv-to-json.html"},
    {"id": "json-validator", "name": "JSON Validator", "cat": "json-data", "badge": "Validator", "desc": "Validate JSON and pinpoint syntax errors by line.", "status": "soon", "url": "/tools/json-data/json-validator.html"},
    {"id": "json-compare", "name": "JSON Compare", "cat": "json-data", "badge": "Utility", "desc": "Diff two JSON documents and highlight changes.", "status": "soon", "url": "/tools/json-data/json-compare.html"},
    {"id": "json-sorter", "name": "JSON Sorter", "cat": "json-data", "badge": "Utility", "desc": "Sort JSON keys and arrays alphabetically.", "status": "soon", "url": "/tools/json-data/json-sorter.html"},
    {"id": "json-keys-extractor", "name": "JSON Keys Extractor", "cat": "json-data", "badge": "Extractor", "desc": "List every key path in a JSON document.", "status": "soon", "url": "/tools/json-data/json-keys-extractor.html"},
    {"id": "json-values-extractor", "name": "JSON Values Extractor", "cat": "json-data", "badge": "Extractor", "desc": "Extract all values from nested JSON.", "status": "soon", "url": "/tools/json-data/json-values-extractor.html"},
    {"id": "json-flatten", "name": "JSON Flatten", "cat": "json-data", "badge": "Converter", "desc": "Flatten nested JSON into dot-notation keys.", "status": "soon", "url": "/tools/json-data/json-flatten.html"},
    {"id": "json-unflatten", "name": "JSON Unflatten", "cat": "json-data", "badge": "Converter", "desc": "Rebuild nested JSON from dot-notation keys.", "status": "soon", "url": "/tools/json-data/json-unflatten.html"},
    {"id": "json-to-xml", "name": "JSON to XML", "cat": "json-data", "badge": "Converter", "desc": "Convert JSON objects into well-formed XML.", "status": "soon", "url": "/tools/json-data/json-to-xml.html"},
    {"id": "xml-to-json", "name": "XML to JSON", "cat": "json-data", "badge": "Converter", "desc": "Parse XML documents into JSON.", "status": "soon", "url": "/tools/json-data/xml-to-json.html"},
    {"id": "json-escape-unescape", "name": "JSON Escape/Unescape", "cat": "json-data", "badge": "Encoder", "desc": "Escape JSON for embedding in strings, or reverse it.", "status": "soon", "url": "/tools/json-data/json-escape-unescape.html"},
    {"id": "json-path-tester", "name": "JSON Path Tester", "cat": "json-data", "badge": "Tester", "desc": "Query JSON with JSONPath expressions.", "status": "soon", "url": "/tools/json-data/json-path-tester.html"},
    {"id": "json-schema-validator", "name": "JSON Schema Validator", "cat": "json-data", "badge": "Validator", "desc": "Validate JSON data against a JSON Schema.", "status": "soon", "url": "/tools/json-data/json-schema-validator.html"},
    {"id": "json-schema-generator", "name": "JSON Schema Generator", "cat": "json-data", "badge": "Generator", "desc": "Infer a JSON Schema from sample data.", "status": "soon", "url": "/tools/json-data/json-schema-generator.html"},
    {"id": "csv-formatter", "name": "CSV Formatter", "cat": "json-data", "badge": "Formatter", "desc": "Align and clean CSV data into readable columns.", "status": "soon", "url": "/tools/json-data/csv-formatter.html"},
    {"id": "csv-validator", "name": "CSV Validator", "cat": "json-data", "badge": "Validator", "desc": "Check CSV for column-count and quoting errors.", "status": "soon", "url": "/tools/json-data/csv-validator.html"},
    // ── Developer ────────────────────────────────────────
    {"id": "base64-encoder", "name": "Base64 Encoder", "cat": "developer", "badge": "Encoder", "desc": "Encode text or data to Base64.", "status": "soon", "url": "/tools/developer/base64-encoder.html"},
    {"id": "base64-decoder", "name": "Base64 Decoder", "cat": "developer", "badge": "Decoder", "desc": "Decode Base64 strings back to text.", "status": "soon", "url": "/tools/developer/base64-decoder.html"},
    {"id": "url-encoder", "name": "URL Encoder", "cat": "developer", "badge": "Encoder", "desc": "Percent-encode text for safe use in URLs.", "status": "soon", "url": "/tools/developer/url-encoder.html"},
    {"id": "url-decoder", "name": "URL Decoder", "cat": "developer", "badge": "Decoder", "desc": "Decode percent-encoded URL strings.", "status": "soon", "url": "/tools/developer/url-decoder.html"},
    {"id": "url-parser", "name": "URL Parser", "cat": "developer", "badge": "Parser", "desc": "Break a URL into protocol, host, path, query and hash.", "status": "soon", "url": "/tools/developer/url-parser.html"},
    {"id": "query-string-parser", "name": "Query String Parser", "cat": "developer", "badge": "Parser", "desc": "Turn a query string into a readable key/value table.", "status": "soon", "url": "/tools/developer/query-string-parser.html"},
    {"id": "query-string-builder", "name": "Query String Builder", "cat": "developer", "badge": "Generator", "desc": "Build encoded query strings from key/value pairs.", "status": "soon", "url": "/tools/developer/query-string-builder.html"},
    {"id": "jwt-decoder", "name": "JWT Decoder", "cat": "developer", "badge": "Decoder", "desc": "Decode JWT payloads and inspect claims and expiry.", "status": "soon", "url": "/tools/developer/jwt-decoder.html"},
    {"id": "jwt-header-decoder", "name": "JWT Header Decoder", "cat": "developer", "badge": "Decoder", "desc": "Inspect the algorithm and type in a JWT header.", "status": "soon", "url": "/tools/developer/jwt-header-decoder.html"},
    {"id": "uuid-generator", "name": "UUID Generator", "cat": "developer", "badge": "Generator", "desc": "Generate random v4 UUIDs in bulk.", "status": "soon", "url": "/tools/developer/uuid-generator.html"},
    {"id": "uuid-validator", "name": "UUID Validator", "cat": "developer", "badge": "Validator", "desc": "Check whether a string is a valid UUID and its version.", "status": "soon", "url": "/tools/developer/uuid-validator.html"},
    {"id": "regex-tester", "name": "Regex Tester", "cat": "developer", "badge": "Tester", "desc": "Test regular expressions with match and group output.", "status": "soon", "url": "/tools/developer/regex-tester.html"},
    {"id": "regex-escape", "name": "Regex Escape", "cat": "developer", "badge": "Encoder", "desc": "Escape special characters for use inside a regex.", "status": "soon", "url": "/tools/developer/regex-escape.html"},
    {"id": "sha-256-hash-generator", "name": "SHA-256 Hash Generator", "cat": "developer", "badge": "Generator", "desc": "Generate SHA-256 hashes from text.", "status": "soon", "url": "/tools/developer/sha-256-hash-generator.html"},
    {"id": "sha-512-hash-generator", "name": "SHA-512 Hash Generator", "cat": "developer", "badge": "Generator", "desc": "Generate SHA-512 hashes from text.", "status": "soon", "url": "/tools/developer/sha-512-hash-generator.html"},
    {"id": "md5-hash-generator", "name": "MD5 Hash Generator", "cat": "developer", "badge": "Generator", "desc": "Generate MD5 checksums from text.", "status": "soon", "url": "/tools/developer/md5-hash-generator.html"},
    {"id": "unix-timestamp-converter", "name": "Unix Timestamp Converter", "cat": "developer", "badge": "Converter", "desc": "Convert Unix timestamps to dates and back.", "status": "soon", "url": "/tools/developer/unix-timestamp-converter.html"},
    {"id": "unix-timestamp-generator", "name": "Unix Timestamp Generator", "cat": "developer", "badge": "Generator", "desc": "Get the current or a custom Unix timestamp.", "status": "soon", "url": "/tools/developer/unix-timestamp-generator.html"},
    {"id": "unicode-escape-unescape", "name": "Unicode Escape/Unescape", "cat": "developer", "badge": "Encoder", "desc": "Convert text to and from Unicode escape sequences.", "status": "soon", "url": "/tools/developer/unicode-escape-unescape.html"},
    {"id": "html-escape-unescape", "name": "HTML Escape/Unescape", "cat": "developer", "badge": "Encoder", "desc": "Escape or unescape HTML special characters.", "status": "soon", "url": "/tools/developer/html-escape-unescape.html"},
    {"id": "mime-type-lookup", "name": "MIME Type Lookup", "cat": "developer", "badge": "Lookup", "desc": "Find the MIME type for any file extension.", "status": "soon", "url": "/tools/developer/mime-type-lookup.html"},
    {"id": "http-status-code-lookup", "name": "HTTP Status Code Lookup", "cat": "developer", "badge": "Lookup", "desc": "Look up the meaning of any HTTP status code.", "status": "soon", "url": "/tools/developer/http-status-code-lookup.html"},
    {"id": "cron-expression-generator", "name": "Cron Expression Generator", "cat": "developer", "badge": "Generator", "desc": "Build and explain cron schedules visually.", "status": "soon", "url": "/tools/developer/cron-expression-generator.html"},
    // ── SEO ────────────────────────────────────────
    {"id": "meta-tag-generator", "name": "Meta Tag Generator", "cat": "seo", "badge": "Generator", "desc": "Generate title, description and essential meta tags.", "status": "soon", "url": "/tools/seo/meta-tag-generator.html"},
    {"id": "open-graph-generator", "name": "Open Graph Generator", "cat": "seo", "badge": "Generator", "desc": "Create og: tags for rich link previews.", "status": "soon", "url": "/tools/seo/open-graph-generator.html"},
    {"id": "twitter-card-generator", "name": "Twitter Card Generator", "cat": "seo", "badge": "Generator", "desc": "Generate Twitter/X card meta tags.", "status": "soon", "url": "/tools/seo/twitter-card-generator.html"},
    {"id": "schema-markup-generator", "name": "Schema Markup Generator", "cat": "seo", "badge": "Generator", "desc": "Generate JSON-LD structured data for any page.", "status": "soon", "url": "/tools/seo/schema-markup-generator.html"},
    {"id": "faq-schema-generator", "name": "FAQ Schema Generator", "cat": "seo", "badge": "Generator", "desc": "Build FAQPage JSON-LD for rich results.", "status": "soon", "url": "/tools/seo/faq-schema-generator.html"},
    {"id": "article-schema-generator", "name": "Article Schema Generator", "cat": "seo", "badge": "Generator", "desc": "Create Article and BlogPosting structured data.", "status": "soon", "url": "/tools/seo/article-schema-generator.html"},
    {"id": "breadcrumb-schema-generator", "name": "Breadcrumb Schema Generator", "cat": "seo", "badge": "Generator", "desc": "Generate BreadcrumbList JSON-LD.", "status": "soon", "url": "/tools/seo/breadcrumb-schema-generator.html"},
    {"id": "local-business-schema-generator", "name": "Local Business Schema Generator", "cat": "seo", "badge": "Generator", "desc": "Structured data for local businesses.", "status": "soon", "url": "/tools/seo/local-business-schema-generator.html"},
    {"id": "organization-schema-generator", "name": "Organization Schema Generator", "cat": "seo", "badge": "Generator", "desc": "Organization JSON-LD with logo and socials.", "status": "soon", "url": "/tools/seo/organization-schema-generator.html"},
    {"id": "product-schema-generator", "name": "Product Schema Generator", "cat": "seo", "badge": "Generator", "desc": "Product structured data with price and reviews.", "status": "soon", "url": "/tools/seo/product-schema-generator.html"},
    {"id": "robots-txt-generator", "name": "Robots.txt Generator", "cat": "seo", "badge": "Generator", "desc": "Create robots.txt rules for crawlers.", "status": "soon", "url": "/tools/seo/robots-txt-generator.html"},
    {"id": "xml-sitemap-generator", "name": "XML Sitemap Generator", "cat": "seo", "badge": "Generator", "desc": "Generate an XML sitemap from a list of URLs.", "status": "soon", "url": "/tools/seo/xml-sitemap-generator.html"},
    {"id": "seo-slug-generator", "name": "SEO Slug Generator", "cat": "seo", "badge": "Generator", "desc": "Turn titles into clean, SEO-friendly URL slugs.", "status": "soon", "url": "/tools/seo/seo-slug-generator.html"},
    {"id": "meta-tag-analyzer", "name": "Meta Tag Analyzer", "cat": "seo", "badge": "Analyzer", "desc": "Analyze meta tags in HTML for SEO issues.", "status": "soon", "url": "/tools/seo/meta-tag-analyzer.html"},
    {"id": "heading-structure-analyzer", "name": "Heading Structure Analyzer", "cat": "seo", "badge": "Analyzer", "desc": "Check H1–H6 hierarchy and outline.", "status": "soon", "url": "/tools/seo/heading-structure-analyzer.html"},
    {"id": "keyword-density-checker", "name": "Keyword Density Checker", "cat": "seo", "badge": "Analyzer", "desc": "Measure keyword frequency and density.", "status": "soon", "url": "/tools/seo/keyword-density-checker.html"},
    {"id": "serp-snippet-preview", "name": "SERP Snippet Preview", "cat": "seo", "badge": "Preview", "desc": "Preview how your page appears in Google results.", "status": "soon", "url": "/tools/seo/serp-snippet-preview.html"},
    {"id": "open-graph-preview", "name": "Open Graph Preview", "cat": "seo", "badge": "Preview", "desc": "Preview social share cards before publishing.", "status": "soon", "url": "/tools/seo/open-graph-preview.html"},
    {"id": "canonical-url-checker", "name": "Canonical URL Checker", "cat": "seo", "badge": "Checker", "desc": "Verify canonical tags in your HTML.", "status": "soon", "url": "/tools/seo/canonical-url-checker.html"},
    {"id": "hreflang-generator", "name": "Hreflang Generator", "cat": "seo", "badge": "Generator", "desc": "Generate hreflang tags for multilingual sites.", "status": "soon", "url": "/tools/seo/hreflang-generator.html"},
    // ── Text ────────────────────────────────────────
    {"id": "remove-duplicate-lines", "name": "Remove Duplicate Lines", "cat": "text", "badge": "Cleaner", "desc": "Delete repeated lines while keeping order.", "status": "soon", "url": "/tools/text/remove-duplicate-lines.html"},
    {"id": "sort-lines", "name": "Sort Lines Alphabetically", "cat": "text", "badge": "Utility", "desc": "Sort lines A–Z, Z–A, naturally or by length.", "status": "soon", "url": "/tools/text/sort-lines.html"},
    {"id": "remove-empty-lines", "name": "Remove Empty Lines", "cat": "text", "badge": "Cleaner", "desc": "Strip blank and whitespace-only lines.", "status": "soon", "url": "/tools/text/remove-empty-lines.html"},
    {"id": "extract-emails", "name": "Extract Emails", "cat": "text", "badge": "Extractor", "desc": "Pull every email address out of any text.", "status": "soon", "url": "/tools/text/extract-emails.html"},
    {"id": "extract-urls", "name": "Extract URLs", "cat": "text", "badge": "Extractor", "desc": "Find and list all URLs in a block of text.", "status": "soon", "url": "/tools/text/extract-urls.html"},
    {"id": "extract-phone-numbers", "name": "Extract Phone Numbers", "cat": "text", "badge": "Extractor", "desc": "Extract phone numbers in common formats.", "status": "soon", "url": "/tools/text/extract-phone-numbers.html"},
    {"id": "find-and-replace", "name": "Find & Replace", "cat": "text", "badge": "Utility", "desc": "Find and replace text with optional regex support.", "status": "soon", "url": "/tools/text/find-and-replace.html"},
    {"id": "text-diff-checker", "name": "Text Diff Checker", "cat": "text", "badge": "Checker", "desc": "Compare two texts and highlight differences.", "status": "soon", "url": "/tools/text/text-diff-checker.html"},
    {"id": "remove-extra-spaces", "name": "Remove Extra Spaces", "cat": "text", "badge": "Cleaner", "desc": "Collapse repeated spaces and trim lines.", "status": "soon", "url": "/tools/text/remove-extra-spaces.html"},
    {"id": "text-to-slug", "name": "Text to Slug", "cat": "text", "badge": "Converter", "desc": "Convert any text into a URL-friendly slug.", "status": "soon", "url": "/tools/text/text-to-slug.html"},
    {"id": "case-converter", "name": "Case Converter", "cat": "text", "badge": "Converter", "desc": "UPPER, lower, Title, camelCase, snake_case and more.", "status": "soon", "url": "/tools/text/case-converter.html"},
    {"id": "line-counter", "name": "Line Counter", "cat": "text", "badge": "Counter", "desc": "Count total, empty and non-empty lines.", "status": "soon", "url": "/tools/text/line-counter.html"},
    {"id": "word-counter", "name": "Word Counter", "cat": "text", "badge": "Counter", "desc": "Count words, sentences and reading time.", "status": "soon", "url": "/tools/text/word-counter.html"},
    {"id": "character-counter", "name": "Character Counter", "cat": "text", "badge": "Counter", "desc": "Count characters with and without spaces.", "status": "soon", "url": "/tools/text/character-counter.html"},
    {"id": "text-to-html", "name": "Text → HTML", "cat": "text", "badge": "Converter", "desc": "Convert plain text into paragraphs and line breaks.", "status": "soon", "url": "/tools/text/text-to-html.html"},
    {"id": "text-to-unicode", "name": "Text → Unicode", "cat": "text", "badge": "Converter", "desc": "Convert text into Unicode code points.", "status": "soon", "url": "/tools/text/text-to-unicode.html"},
    {"id": "unicode-to-text", "name": "Unicode → Text", "cat": "text", "badge": "Converter", "desc": "Convert Unicode code points back to text.", "status": "soon", "url": "/tools/text/unicode-to-text.html"},
    // ── Generators ────────────────────────────────────────
    {"id": "html-boilerplate-generator", "name": "HTML Boilerplate Generator", "cat": "generators", "badge": "Generator", "desc": "Generate a modern HTML5 starter document.", "status": "soon", "url": "/tools/generators/html-boilerplate-generator.html"},
    {"id": "html-table-generator", "name": "HTML Table Generator", "cat": "generators", "badge": "Generator", "desc": "Build semantic HTML5 tables visually in a grid.", "status": "live", "url": "/tools/html/html-table-generator.html"},
    {"id": "html-form-generator", "name": "HTML Form Generator", "cat": "generators", "badge": "Generator", "desc": "Build accessible HTML forms field by field.", "status": "soon", "url": "/tools/generators/html-form-generator.html"},
    {"id": "html-list-generator", "name": "HTML List Generator", "cat": "generators", "badge": "Generator", "desc": "Generate ordered, unordered and nested lists.", "status": "soon", "url": "/tools/generators/html-list-generator.html"},
    {"id": "html-link-generator", "name": "HTML Link Generator", "cat": "generators", "badge": "Generator", "desc": "Create anchor tags with target, rel and title.", "status": "soon", "url": "/tools/generators/html-link-generator.html"},
    {"id": "html-image-tag-generator", "name": "HTML Image Tag Generator", "cat": "generators", "badge": "Generator", "desc": "Generate img tags with alt, srcset and lazy loading.", "status": "soon", "url": "/tools/generators/html-image-tag-generator.html"},
    {"id": "css-button-generator", "name": "CSS Button Generator", "cat": "generators", "badge": "Generator", "desc": "Design buttons with hover states and copy CSS.", "status": "soon", "url": "/tools/generators/css-button-generator.html"},
    {"id": "css-card-generator", "name": "CSS Card Generator", "cat": "generators", "badge": "Generator", "desc": "Generate card components with HTML and CSS.", "status": "soon", "url": "/tools/generators/css-card-generator.html"},
    {"id": "css-navigation-generator", "name": "CSS Navigation Generator", "cat": "generators", "badge": "Generator", "desc": "Build responsive navigation bars.", "status": "soon", "url": "/tools/generators/css-navigation-generator.html"},
    {"id": "css-animation-generator", "name": "CSS Animation Generator", "cat": "generators", "badge": "Generator", "desc": "Create keyframe animations with timing controls.", "status": "soon", "url": "/tools/generators/css-animation-generator.html"},
    {"id": "css-loader-generator", "name": "CSS Loader Generator", "cat": "generators", "badge": "Generator", "desc": "Generate pure-CSS spinners and loaders.", "status": "soon", "url": "/tools/generators/css-loader-generator.html"},
    {"id": "css-tooltip-generator", "name": "CSS Tooltip Generator", "cat": "generators", "badge": "Generator", "desc": "Build CSS-only tooltips in any direction.", "status": "soon", "url": "/tools/generators/css-tooltip-generator.html"},
    {"id": "css-modal-generator", "name": "CSS Modal Generator", "cat": "generators", "badge": "Generator", "desc": "Generate accessible modal dialog markup and CSS.", "status": "soon", "url": "/tools/generators/css-modal-generator.html"},
    {"id": "css-toggle-generator", "name": "CSS Toggle Generator", "cat": "generators", "badge": "Generator", "desc": "Design toggle switches with pure CSS.", "status": "soon", "url": "/tools/generators/css-toggle-generator.html"},
    {"id": "css-checkbox-generator", "name": "CSS Checkbox Generator", "cat": "generators", "badge": "Generator", "desc": "Style custom checkboxes and radio buttons.", "status": "soon", "url": "/tools/generators/css-checkbox-generator.html"},
    {"id": "css-input-generator", "name": "CSS Input Generator", "cat": "generators", "badge": "Generator", "desc": "Style text inputs with focus and error states.", "status": "soon", "url": "/tools/generators/css-input-generator.html"},
    {"id": "favicon-generator", "name": "Favicon Generator", "cat": "generators", "badge": "Generator", "desc": "Generate favicon sizes and the HTML link tags.", "status": "soon", "url": "/tools/generators/favicon-generator.html"},
    {"id": "svg-icon-generator", "name": "SVG Icon Generator", "cat": "generators", "badge": "Generator", "desc": "Create simple SVG icons and export the code.", "status": "soon", "url": "/tools/generators/svg-icon-generator.html"},
  ];

  // Display order of tools inside each category page
  var CATEGORY_TOOLS = {
    "html-web": ["html-validator", "html-formatter", "html-minifier", "html-to-markdown", "html-to-text", "html-to-jsx", "html-to-css", "html-entity-encoder", "html-entity-decoder", "html-link-extractor", "html-image-extractor", "html-heading-extractor", "html-meta-tag-extractor", "html-comment-remover", "html-duplicate-id-checker", "html-favicon-extractor"],
    "css": ["css-formatter", "css-minifier", "css-gradient-generator", "css-box-shadow-generator", "css-border-radius-generator", "css-flexbox-generator", "css-grid-generator", "css-clip-path-generator", "css-transform-generator", "css-filter-generator", "css-glassmorphism-generator", "css-neumorphism-generator", "css-clamp-generator", "css-media-query-generator", "css-color-extractor"],
    "javascript": ["javascript-formatter", "javascript-minifier", "javascript-validator", "json-js-object-converter", "js-escape-unescape", "javascript-array-utilities", "javascript-object-key-sorter", "javascript-regex-tester", "js-timestamp-converter", "js-unicode-escape-tool"],
    "json-data": ["json-formatter", "json-minifier", "json-to-yaml", "yaml-to-json", "json-to-csv", "csv-to-json", "json-validator", "json-compare", "json-sorter", "json-keys-extractor", "json-values-extractor", "json-flatten", "json-unflatten", "json-to-xml", "xml-to-json", "json-escape-unescape", "json-path-tester", "json-schema-validator", "json-schema-generator", "csv-formatter", "csv-validator"],
    "developer": ["base64-encoder", "base64-decoder", "url-encoder", "url-decoder", "url-parser", "query-string-parser", "query-string-builder", "jwt-decoder", "jwt-header-decoder", "uuid-generator", "uuid-validator", "regex-tester", "regex-escape", "sha-256-hash-generator", "sha-512-hash-generator", "md5-hash-generator", "unix-timestamp-converter", "unix-timestamp-generator", "unicode-escape-unescape", "html-escape-unescape", "mime-type-lookup", "http-status-code-lookup", "cron-expression-generator"],
    "seo": ["meta-tag-generator", "open-graph-generator", "twitter-card-generator", "schema-markup-generator", "faq-schema-generator", "article-schema-generator", "breadcrumb-schema-generator", "local-business-schema-generator", "organization-schema-generator", "product-schema-generator", "robots-txt-generator", "xml-sitemap-generator", "seo-slug-generator", "meta-tag-analyzer", "heading-structure-analyzer", "keyword-density-checker", "serp-snippet-preview", "open-graph-preview", "canonical-url-checker", "hreflang-generator"],
    "text": ["remove-duplicate-lines", "sort-lines", "remove-empty-lines", "extract-emails", "extract-urls", "extract-phone-numbers", "find-and-replace", "text-diff-checker", "remove-extra-spaces", "text-to-slug", "case-converter", "line-counter", "word-counter", "character-counter", "text-to-html", "text-to-unicode", "unicode-to-text"],
    "generators": ["html-boilerplate-generator", "html-table-generator", "html-form-generator", "html-list-generator", "html-link-generator", "html-image-tag-generator", "css-button-generator", "css-card-generator", "css-navigation-generator", "css-grid-generator", "css-flexbox-generator", "css-gradient-generator", "css-animation-generator", "css-loader-generator", "css-tooltip-generator", "css-modal-generator", "css-toggle-generator", "css-checkbox-generator", "css-input-generator", "favicon-generator", "svg-icon-generator"],
  };

  // Header navigation. type:'categories' = all categories; type:'category' = tools of one category;
  // type:'tools' = hand-picked tool ids.
  var NAV = [
    { label: "Categories", type: "categories" },
    { label: "HTML & CSS", type: "tools",
      tools: ["html-formatter","html-minifier","html-validator","html-to-markdown","html-to-jsx","html-to-css",
              "html-link-extractor","html-image-extractor","css-formatter","css-minifier","css-gradient-generator","css-grid-generator"],
      footer: [{ cat: "html-web" }, { cat: "css" }] },
    { label: "JSON & Data", type: "category", cat: "json-data", limit: 12 },
    { label: "Developer", type: "category", cat: "developer", limit: 12 },
    { label: "SEO", type: "category", cat: "seo", limit: 12 },
    { label: "Generators", type: "category", cat: "generators", limit: 12 }
  ];

  window.TOOLYARD_DATA = { categories: CATEGORIES, tools: TOOLS, categoryTools: CATEGORY_TOOLS, nav: NAV };
})();
